import { resolveVuetifyTheme } from '@core/utils/vuetify'

export const staticPrimaryColor = '#5B2C91'

const theme = {
  defaultTheme: resolveVuetifyTheme(),
  themes: {
    light: {
      dark: false,
      colors: {
        'primary': staticPrimaryColor,
        'on-primary': '#fff',
        'secondary': '#6B7280',
        'on-secondary': '#fff',
        'success': '#1FA86C',
        'on-success': '#fff',
        'info': '#2F7DE1',
        'on-info': '#fff',
        'warning': '#E08A1E',
        'on-warning': '#fff',
        'error': '#D64545',
        'background': '#F6F5F8',
        'on-background': '#1C1428',
        'surface': '#FFFFFF',
        'on-surface': '#1C1428',
        'on-hover': '#EDE9F4',
        'grey-50': '#FAFAFA',
        'grey-100': '#F5F5F5',
        'grey-200': '#EEEEEE',
        'grey-300': '#E0E0E0',
        'grey-400': '#BDBDBD',
        'grey-500': '#9E9E9E',
        'grey-600': '#757575',
        'grey-700': '#616161',
        'grey-800': '#424242',
        'grey-900': '#212121',
        'perfect-scrollbar-thumb': '#D6D2DE',
        'skin-bordered-background': '#fff',
        'skin-bordered-surface': '#fff',
      },
      variables: {
        'code-color': '#5B2C91',
        'overlay-scrim-background': '#1C1428',
        'tooltip-background': '#2A2040',
        'overlay-scrim-opacity': 0.45,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.06,
        'activated-opacity': 0.16,
        'pressed-opacity': 0.14,
        'dragged-opacity': 0.1,
        'disabled-opacity': 0.42,
        'border-color': '#2F2B3D',
        'border-opacity': 0.1,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.68,
        'switch-opacity': 0.2,
        'switch-disabled-track-opacity': 0.3,
        'switch-disabled-thumb-opacity': 0.4,
        'switch-checked-disabled-opacity': 0.3,

        // Shadows
        'shadow-key-umbra-color': '#2F2B3D',
      },
    },
    dark: {
      dark: true,
      colors: {
        'primary': '#9B7AD8',
        'on-primary': '#1C1428',
        'secondary': '#A3A8B5',
        'on-secondary': '#1C1428',
        'success': '#3DCF8E',
        'on-success': '#0B1F16',
        'info': '#6BA6F0',
        'on-info': '#0B1728',
        'warning': '#F0B45A',
        'on-warning': '#2A1B08',
        'error': '#F07171',
        'background': '#1A1524',
        'on-background': '#E8E4F0',
        'surface': '#241E32',
        'on-surface': '#E8E4F0',
        'on-hover': '#808080',
        'grey-50': '#26293A',
        'grey-100': '#2F3349',
        'grey-200': '#26293A',
        'grey-300': '#4A5072',
        'grey-400': '#5E6692',
        'grey-500': '#7983BB',
        'grey-600': '#AAB3DE',
        'grey-700': '#B6BEE3',
        'grey-800': '#CFD3EC',
        'grey-900': '#E7E9F6',
        'perfect-scrollbar-thumb': '#4A5072',
        'skin-bordered-background': '#2f3349',
        'skin-bordered-surface': '#2f3349',
      },
      variables: {
        'code-color': '#d400ff',
        'overlay-scrim-background': '#101121',
        'tooltip-background': '#5E6692',
        'overlay-scrim-opacity': 0.6,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.06,
        'activated-opacity': 0.16,
        'pressed-opacity': 0.14,
        'dragged-opacity': 0.1,
        'disabled-opacity': 0.42,
        'border-color': '#D0D4F1',
        'border-opacity': 0.16,
        'high-emphasis-opacity': 0.87,
        'medium-emphasis-opacity': 0.68,
        'switch-opacity': 0.4,
        'switch-disabled-track-opacity': 0.4,
        'switch-disabled-thumb-opacity': 0.8,
        'switch-checked-disabled-opacity': 0.3,

        // Shadows
        'shadow-key-umbra-color': '#0F1422',
      },
    },
  },
}

export default theme
